export enum RegisterActionTypes {
    STORE_FAILED_VERIFICATION = "STORE_FAILED_VERIFICATION",
    STORE_SIGNING_KEY_MNEMONIC = "ADD_SIGNING_MNEMONIC",
    STORE_SIGNING_KEY = "STORE_SIGNING_KEY",
    STORE_WITHDRAWAL_KEY = "STORE_WITHDRAWAL_KEY",
    CLEAR_KEYS = "CLEAR_KEYS"
}

export enum DepositActionTypes {
    GENERATE_DEPOSIT = "GENERATE_DEPOSIT",
    DEPOSIT_TRANSACTION = "DEPOSIT_TRANSACTION",
    DEPOSIT_VISIBLE = "DEPOSIT_VISIBLE"
}