version: "3.0"

####
# https://github.com/sigp/lighthouse-docker
# https://github.com/sigp/lighthouse/tree/master/scripts/local_testnet

services:
  beacon_node:
    image: sigp/lighthouse
    container_name: "testnet_beacon"
    volumes:
      - ./testnet/data:/root/testnet
      - ./testnet/beacon:/root/beacon
      - ./testnet:/root/scripts
    ports:
      - 5052:5052/tcp
      - 5053:5053/tcp
      - 9000:9000/tcp
      - 9000:9000/udp
    env_file: testnet/vars.env
    command: sh /root/scripts/start-beacon-node.sh
    restart: on-failure

  validator_client:
    image: sigp/lighthouse
    container_name: "testnet_validator"
    volumes:
      - ./testnet/validators:/root/validators
      - ./testnet/secrets:/root/secrets
      - ./testnet:/root/scripts
    depends_on:
      - beacon_node
    env_file: testnet/vars.env
    command: sh /root/scripts/start-validator-client.sh
    restart: on-failure
