version: "3.0"

####
# https://github.com/sigp/lighthouse-docker
# https://github.com/sigp/lighthouse/tree/master/scripts/local_testnet

services:
  beacon_node:
    image: "${DOCKER_LIGHTHOUSE_IMAGE}"
    container_name: "testnet_beacon"
    volumes:
      - ./testnet/data:/root/testnet
      - ./testnet/beacon:/root/beacon
      - ./testnet:/root/scripts
    ports:
      - 5052:5052/tcp
    env_file:
      - testnet/vars.env
      - .env
    command: sh /root/scripts/start-beacon-node.sh
    restart: on-failure

  validator_client:
    image: "${DOCKER_LIGHTHOUSE_IMAGE}"
    container_name: "testnet_validator"
    volumes:
      - ./testnet/data:/root/testnet
      - ./testnet/validators:/root/validators
      - ./testnet/secrets:/root/secrets
      - ./testnet:/root/scripts
    depends_on:
      - beacon_node
    env_file:
      - testnet/vars.env
      - .env
    command: sh /root/scripts/start-validator-client.sh
    restart: on-failure
