import {
    Attestation,
    AttestationData,
    AttesterSlashing,
    Deposit,
    GetBlock,
    IndexedAttestation,
    ProposerSlashing,
    SignedBeaconBlockHeader,
    SignedVoluntaryExit,
} from "./types";
import {base64ToHex} from "./utils";

/* eslint-disable camelcase */
/* eslint-disable @typescript-eslint/camelcase */

// TODO: after complete all mappings change return type "Block" to "Json"
export const mapProduceBlockResponseToStandardProduceBlockResponse = (data: GetBlock): Block => ({
    // TODO: get a way to get signature :man_shrugging:
    signature: "",
    message: {
        slot: data.slot,
        proposer_index: data.proposer_index,
        parent_root: base64ToHex(data.parent_root),
        state_root: base64ToHex(data.state_root),
        body: {
            randao_reveal: base64ToHex(data.body.randao_reveal),
            graffiti: base64ToHex(data.body.graffiti),
            eth1_data: {
                deposit_root: base64ToHex(data.body.eth1_data.deposit_root),
                deposit_count: data.body.eth1_data.deposit_count,
                block_hash: base64ToHex(data.body.eth1_data.block_hash),
            },
            proposer_slashings: data.body.proposer_slashings.map(mapProposerSlashing),
            attester_slashings: data.body.attester_slashings.map(mapAttesterSlashing),
            attestations: data.body.attestations.map(mapAttestation),
            deposits: data.body.deposits.map(mapDeposit),
            voluntary_exits: data.body.voluntary_exits.map(mapVoluntaryExit),
        },
    },
});

export const mapProposerSlashing = (proposerSlashing: ProposerSlashing): ProposerSlashingsEntity => ({
    signed_header_1: mapSignedHeader(proposerSlashing.header_1),
    signed_header_2: mapSignedHeader(proposerSlashing.header_2),
});

export const mapSignedHeader = (signedHeader: SignedBeaconBlockHeader): SignedHeader1OrSignedHeader2 => ({
    message: {
        slot: signedHeader.header.slot,
        proposer_index: signedHeader.header.proposer_index,
        parent_root: signedHeader.header.parent_root,
        state_root: signedHeader.header.body_root,
        body_root: signedHeader.header.body_root,
    },
    signature: signedHeader.signature,
});

export const mapAttesterSlashing = (attesterSlashing: AttesterSlashing): AttesterSlashingsEntity => ({
    attestation_1: mapAttesterSlashingAttestation(attesterSlashing.attestation_1),
    attestation_2: mapAttesterSlashingAttestation(attesterSlashing.attestation_2),
});

export const mapAttesterSlashingAttestation = (attesterSlashing: IndexedAttestation): Attestation1OrAttestation2 => ({
    attesting_indices: attesterSlashing.attesting_indices || [],
    signature: attesterSlashing.signature,
    data: mapAttestationData(attesterSlashing.data),
});

export const mapAttestation = (attestation: Attestation): AttestationsEntity => ({
    aggregation_bits: base64ToHex(attestation.aggregation_bits),
    signature: base64ToHex(attestation.signature),
    data: mapAttestationData(attestation.data),
});

export const mapAttestationData = (data: AttestationData): Data1 => ({
    slot: data.slot,
    index: data.committee_index,
    beacon_block_root: base64ToHex(data.beacon_block_root),
    source: {
        epoch: data.source.epoch,
        root: base64ToHex(data.source.root),
    },
    target: {
        epoch: data.target.epoch,
        root: base64ToHex(data.target.root),
    },
});

export const mapDeposit = (deposit: Deposit): DepositsEntity => ({
    proof: deposit.proof || [],
    data: {
        pubkey: base64ToHex(deposit.data.public_key),
        withdrawal_credentials: base64ToHex(deposit.data.withdrawal_credentials),
        amount: deposit.data.amount,
        signature: base64ToHex(deposit.data.signature),
    },
});

export const mapVoluntaryExit = (voluntaryExit: SignedVoluntaryExit): VoluntaryExitsEntity => ({
    message: {
        epoch: voluntaryExit.exit.epoch,
        validator_index: voluntaryExit.exit.epoch,
    },
    signature: voluntaryExit.signature,
});

// This "garbage" is just here to help me
// autogenerated from eth2 getBlock json

/* eslint-disable @typescript-eslint/interface-name-prefix */
export interface Block {
    message: Message;
    signature: string;
}
export interface Message {
    slot: string;
    proposer_index: string;
    parent_root: string;
    state_root: string;
    body: Body;
}
export interface Body {
    randao_reveal: string;
    eth1_data: Eth1Data;
    graffiti: string;
    proposer_slashings?: ProposerSlashingsEntity[] | null;
    attester_slashings?: AttesterSlashingsEntity[] | null;
    attestations?: AttestationsEntity[] | null;
    deposits?: DepositsEntity[] | null;
    voluntary_exits?: VoluntaryExitsEntity[] | null;
}
export interface Eth1Data {
    deposit_root: string;
    deposit_count: string;
    block_hash: string;
}
export interface ProposerSlashingsEntity {
    signed_header_1: SignedHeader1OrSignedHeader2;
    signed_header_2: SignedHeader1OrSignedHeader2;
}
export interface SignedHeader1OrSignedHeader2 {
    message: Message1;
    signature: string;
}
export interface Message1 {
    slot: string;
    proposer_index: string;
    parent_root: string;
    state_root: string;
    body_root: string;
}
export interface AttesterSlashingsEntity {
    attestation_1: Attestation1OrAttestation2;
    attestation_2: Attestation1OrAttestation2;
}
export interface Attestation1OrAttestation2 {
    attesting_indices?: string[] | null;
    signature: string;
    data: Data1;
}
export interface Data1 {
    slot: string;
    index: string;
    beacon_block_root: string;
    source: SourceOrTarget;
    target: SourceOrTarget;
}
export interface SourceOrTarget {
    epoch: string;
    root: string;
}
export interface AttestationsEntity {
    aggregation_bits: string;
    signature: string;
    data: Data1;
}
export interface DepositsEntity {
    proof?: string[] | null;
    data: Data2;
}
export interface Data2 {
    pubkey: string;
    withdrawal_credentials: string;
    amount: string;
    signature: string;
}
export interface VoluntaryExitsEntity {
    message: Message2;
    signature: string;
}
export interface Message2 {
    epoch: string;
    validator_index: string;
}
