export enum IpcDatabaseEvents {
    DATABASE_GET = "CG_DB_GET",
    DATABASE_PUT = "CG_DB_PUT",
    DATABASE_DELETE = "CG_DB_DELETE",
    DATABASE_SEARCH = "CG_DB_SEARCH",
    DATABASE_BATCH_PUT = "CG_DB_BATCH_PUT",
    DATABASE_KEYS = "CG_DB_KEYS",
    DATABASE_VALUES = "CG_DB_VALUES",
    DATABASE_VALUES_STREAM = "CG_DB_VALUES",
    DATABASE_VALUES_EVENT = "CG_DB_VALUES_EVENT",
}
